/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthProfileRouteImport } from './routes/_auth/_profile'
import { Route as AuthOrganizationsIndexRouteImport } from './routes/_auth/organizations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthOrganizationsOrganizationSlugLayoutRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout'
import { Route as AuthProfileUserIdOrganizationsRouteImport } from './routes/_auth/_profile/$userId/organizations'
import { Route as AuthProfileUserIdInvitationsRouteImport } from './routes/_auth/_profile/$userId/invitations'
import { Route as AuthProfileUserIdAccountRouteImport } from './routes/_auth/_profile/$userId/account'
import { Route as AuthOrganizationsOrganizationSlugLayoutIndexRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/index'
import { Route as AuthOrganizationsOrganizationSlugLayoutManageRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/_manage'
import { Route as AuthOrganizationsOrganizationSlugLayoutProjectsIndexRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/projects/index'
import { Route as AuthOrganizationsOrganizationSlugLayoutManageSettingsRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/_manage/settings'
import { Route as AuthOrganizationsOrganizationSlugLayoutManageMembersRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/_manage/members'
import { Route as AuthOrganizationsOrganizationSlugLayoutManageInvitationsRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/_manage/invitations'
import { Route as AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/index'
import { Route as AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/settings'
import { Route as AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRouteImport } from './routes/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/$feedbackId'

const AuthOrganizationsOrganizationSlugRouteImport = createFileRoute(
  '/_auth/organizations/$organizationSlug',
)()

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/_profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationsOrganizationSlugRoute =
  AuthOrganizationsOrganizationSlugRouteImport.update({
    id: '/organizations/$organizationSlug',
    path: '/organizations/$organizationSlug',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOrganizationsIndexRoute = AuthOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizationsOrganizationSlugLayoutRoute =
  AuthOrganizationsOrganizationSlugLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthOrganizationsOrganizationSlugRoute,
  } as any)
const AuthProfileUserIdOrganizationsRoute =
  AuthProfileUserIdOrganizationsRouteImport.update({
    id: '/$userId/organizations',
    path: '/$userId/organizations',
    getParentRoute: () => AuthProfileRoute,
  } as any)
const AuthProfileUserIdInvitationsRoute =
  AuthProfileUserIdInvitationsRouteImport.update({
    id: '/$userId/invitations',
    path: '/$userId/invitations',
    getParentRoute: () => AuthProfileRoute,
  } as any)
const AuthProfileUserIdAccountRoute =
  AuthProfileUserIdAccountRouteImport.update({
    id: '/$userId/account',
    path: '/$userId/account',
    getParentRoute: () => AuthProfileRoute,
  } as any)
const AuthOrganizationsOrganizationSlugLayoutIndexRoute =
  AuthOrganizationsOrganizationSlugLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutRoute,
  } as any)
const AuthOrganizationsOrganizationSlugLayoutManageRoute =
  AuthOrganizationsOrganizationSlugLayoutManageRouteImport.update({
    id: '/_manage',
    getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutRoute,
  } as any)
const AuthOrganizationsOrganizationSlugLayoutProjectsIndexRoute =
  AuthOrganizationsOrganizationSlugLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutRoute,
  } as any)
const AuthOrganizationsOrganizationSlugLayoutManageSettingsRoute =
  AuthOrganizationsOrganizationSlugLayoutManageSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutManageRoute,
  } as any)
const AuthOrganizationsOrganizationSlugLayoutManageMembersRoute =
  AuthOrganizationsOrganizationSlugLayoutManageMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutManageRoute,
  } as any)
const AuthOrganizationsOrganizationSlugLayoutManageInvitationsRoute =
  AuthOrganizationsOrganizationSlugLayoutManageInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutManageRoute,
  } as any)
const AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRoute =
  AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRouteImport.update(
    {
      id: '/projects/$projectSlug/',
      path: '/projects/$projectSlug/',
      getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutRoute,
    } as any,
  )
const AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRoute =
  AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRouteImport.update(
    {
      id: '/projects/$projectSlug/settings',
      path: '/projects/$projectSlug/settings',
      getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutRoute,
    } as any,
  )
const AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRoute =
  AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRouteImport.update(
    {
      id: '/projects/$projectSlug/$feedbackId',
      path: '/projects/$projectSlug/$feedbackId',
      getParentRoute: () => AuthOrganizationsOrganizationSlugLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations': typeof AuthOrganizationsIndexRoute
  '/$userId/account': typeof AuthProfileUserIdAccountRoute
  '/$userId/invitations': typeof AuthProfileUserIdInvitationsRoute
  '/$userId/organizations': typeof AuthProfileUserIdOrganizationsRoute
  '/organizations/$organizationSlug': typeof AuthOrganizationsOrganizationSlugLayoutManageRouteWithChildren
  '/organizations/$organizationSlug/': typeof AuthOrganizationsOrganizationSlugLayoutIndexRoute
  '/organizations/$organizationSlug/invitations': typeof AuthOrganizationsOrganizationSlugLayoutManageInvitationsRoute
  '/organizations/$organizationSlug/members': typeof AuthOrganizationsOrganizationSlugLayoutManageMembersRoute
  '/organizations/$organizationSlug/settings': typeof AuthOrganizationsOrganizationSlugLayoutManageSettingsRoute
  '/organizations/$organizationSlug/projects': typeof AuthOrganizationsOrganizationSlugLayoutProjectsIndexRoute
  '/organizations/$organizationSlug/projects/$projectSlug/$feedbackId': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRoute
  '/organizations/$organizationSlug/projects/$projectSlug/settings': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRoute
  '/organizations/$organizationSlug/projects/$projectSlug': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations': typeof AuthOrganizationsIndexRoute
  '/$userId/account': typeof AuthProfileUserIdAccountRoute
  '/$userId/invitations': typeof AuthProfileUserIdInvitationsRoute
  '/$userId/organizations': typeof AuthProfileUserIdOrganizationsRoute
  '/organizations/$organizationSlug': typeof AuthOrganizationsOrganizationSlugLayoutIndexRoute
  '/organizations/$organizationSlug/invitations': typeof AuthOrganizationsOrganizationSlugLayoutManageInvitationsRoute
  '/organizations/$organizationSlug/members': typeof AuthOrganizationsOrganizationSlugLayoutManageMembersRoute
  '/organizations/$organizationSlug/settings': typeof AuthOrganizationsOrganizationSlugLayoutManageSettingsRoute
  '/organizations/$organizationSlug/projects': typeof AuthOrganizationsOrganizationSlugLayoutProjectsIndexRoute
  '/organizations/$organizationSlug/projects/$projectSlug/$feedbackId': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRoute
  '/organizations/$organizationSlug/projects/$projectSlug/settings': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRoute
  '/organizations/$organizationSlug/projects/$projectSlug': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_auth/_profile': typeof AuthProfileRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/organizations/': typeof AuthOrganizationsIndexRoute
  '/_auth/_profile/$userId/account': typeof AuthProfileUserIdAccountRoute
  '/_auth/_profile/$userId/invitations': typeof AuthProfileUserIdInvitationsRoute
  '/_auth/_profile/$userId/organizations': typeof AuthProfileUserIdOrganizationsRoute
  '/_auth/organizations/$organizationSlug': typeof AuthOrganizationsOrganizationSlugRouteWithChildren
  '/_auth/organizations/$organizationSlug/_layout': typeof AuthOrganizationsOrganizationSlugLayoutRouteWithChildren
  '/_auth/organizations/$organizationSlug/_layout/_manage': typeof AuthOrganizationsOrganizationSlugLayoutManageRouteWithChildren
  '/_auth/organizations/$organizationSlug/_layout/': typeof AuthOrganizationsOrganizationSlugLayoutIndexRoute
  '/_auth/organizations/$organizationSlug/_layout/_manage/invitations': typeof AuthOrganizationsOrganizationSlugLayoutManageInvitationsRoute
  '/_auth/organizations/$organizationSlug/_layout/_manage/members': typeof AuthOrganizationsOrganizationSlugLayoutManageMembersRoute
  '/_auth/organizations/$organizationSlug/_layout/_manage/settings': typeof AuthOrganizationsOrganizationSlugLayoutManageSettingsRoute
  '/_auth/organizations/$organizationSlug/_layout/projects/': typeof AuthOrganizationsOrganizationSlugLayoutProjectsIndexRoute
  '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/$feedbackId': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRoute
  '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/settings': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRoute
  '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/': typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/dashboard'
    | '/api/auth/$'
    | '/organizations'
    | '/$userId/account'
    | '/$userId/invitations'
    | '/$userId/organizations'
    | '/organizations/$organizationSlug'
    | '/organizations/$organizationSlug/'
    | '/organizations/$organizationSlug/invitations'
    | '/organizations/$organizationSlug/members'
    | '/organizations/$organizationSlug/settings'
    | '/organizations/$organizationSlug/projects'
    | '/organizations/$organizationSlug/projects/$projectSlug/$feedbackId'
    | '/organizations/$organizationSlug/projects/$projectSlug/settings'
    | '/organizations/$organizationSlug/projects/$projectSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/dashboard'
    | '/api/auth/$'
    | '/organizations'
    | '/$userId/account'
    | '/$userId/invitations'
    | '/$userId/organizations'
    | '/organizations/$organizationSlug'
    | '/organizations/$organizationSlug/invitations'
    | '/organizations/$organizationSlug/members'
    | '/organizations/$organizationSlug/settings'
    | '/organizations/$organizationSlug/projects'
    | '/organizations/$organizationSlug/projects/$projectSlug/$feedbackId'
    | '/organizations/$organizationSlug/projects/$projectSlug/settings'
    | '/organizations/$organizationSlug/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/pricing'
    | '/_auth/_profile'
    | '/_auth/dashboard'
    | '/api/auth/$'
    | '/_auth/organizations/'
    | '/_auth/_profile/$userId/account'
    | '/_auth/_profile/$userId/invitations'
    | '/_auth/_profile/$userId/organizations'
    | '/_auth/organizations/$organizationSlug'
    | '/_auth/organizations/$organizationSlug/_layout'
    | '/_auth/organizations/$organizationSlug/_layout/_manage'
    | '/_auth/organizations/$organizationSlug/_layout/'
    | '/_auth/organizations/$organizationSlug/_layout/_manage/invitations'
    | '/_auth/organizations/$organizationSlug/_layout/_manage/members'
    | '/_auth/organizations/$organizationSlug/_layout/_manage/settings'
    | '/_auth/organizations/$organizationSlug/_layout/projects/'
    | '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/$feedbackId'
    | '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/settings'
    | '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_profile': {
      id: '/_auth/_profile'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/$organizationSlug': {
      id: '/_auth/organizations/$organizationSlug'
      path: '/organizations/$organizationSlug'
      fullPath: '/organizations/$organizationSlug'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/': {
      id: '/_auth/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthOrganizationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/organizations/$organizationSlug/_layout': {
      id: '/_auth/organizations/$organizationSlug/_layout'
      path: '/organizations/$organizationSlug'
      fullPath: '/organizations/$organizationSlug'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugRoute
    }
    '/_auth/_profile/$userId/organizations': {
      id: '/_auth/_profile/$userId/organizations'
      path: '/$userId/organizations'
      fullPath: '/$userId/organizations'
      preLoaderRoute: typeof AuthProfileUserIdOrganizationsRouteImport
      parentRoute: typeof AuthProfileRoute
    }
    '/_auth/_profile/$userId/invitations': {
      id: '/_auth/_profile/$userId/invitations'
      path: '/$userId/invitations'
      fullPath: '/$userId/invitations'
      preLoaderRoute: typeof AuthProfileUserIdInvitationsRouteImport
      parentRoute: typeof AuthProfileRoute
    }
    '/_auth/_profile/$userId/account': {
      id: '/_auth/_profile/$userId/account'
      path: '/$userId/account'
      fullPath: '/$userId/account'
      preLoaderRoute: typeof AuthProfileUserIdAccountRouteImport
      parentRoute: typeof AuthProfileRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/': {
      id: '/_auth/organizations/$organizationSlug/_layout/'
      path: '/'
      fullPath: '/organizations/$organizationSlug/'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutIndexRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/_manage': {
      id: '/_auth/organizations/$organizationSlug/_layout/_manage'
      path: ''
      fullPath: '/organizations/$organizationSlug'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/projects/': {
      id: '/_auth/organizations/$organizationSlug/_layout/projects/'
      path: '/projects'
      fullPath: '/organizations/$organizationSlug/projects'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutProjectsIndexRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/_manage/settings': {
      id: '/_auth/organizations/$organizationSlug/_layout/_manage/settings'
      path: '/settings'
      fullPath: '/organizations/$organizationSlug/settings'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageSettingsRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/_manage/members': {
      id: '/_auth/organizations/$organizationSlug/_layout/_manage/members'
      path: '/members'
      fullPath: '/organizations/$organizationSlug/members'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageMembersRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/_manage/invitations': {
      id: '/_auth/organizations/$organizationSlug/_layout/_manage/invitations'
      path: '/invitations'
      fullPath: '/organizations/$organizationSlug/invitations'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageInvitationsRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/': {
      id: '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/'
      path: '/projects/$projectSlug'
      fullPath: '/organizations/$organizationSlug/projects/$projectSlug'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/settings': {
      id: '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/settings'
      path: '/projects/$projectSlug/settings'
      fullPath: '/organizations/$organizationSlug/projects/$projectSlug/settings'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutRoute
    }
    '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/$feedbackId': {
      id: '/_auth/organizations/$organizationSlug/_layout/projects/$projectSlug/$feedbackId'
      path: '/projects/$projectSlug/$feedbackId'
      fullPath: '/organizations/$organizationSlug/projects/$projectSlug/$feedbackId'
      preLoaderRoute: typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRouteImport
      parentRoute: typeof AuthOrganizationsOrganizationSlugLayoutRoute
    }
  }
}

interface AuthProfileRouteChildren {
  AuthProfileUserIdAccountRoute: typeof AuthProfileUserIdAccountRoute
  AuthProfileUserIdInvitationsRoute: typeof AuthProfileUserIdInvitationsRoute
  AuthProfileUserIdOrganizationsRoute: typeof AuthProfileUserIdOrganizationsRoute
}

const AuthProfileRouteChildren: AuthProfileRouteChildren = {
  AuthProfileUserIdAccountRoute: AuthProfileUserIdAccountRoute,
  AuthProfileUserIdInvitationsRoute: AuthProfileUserIdInvitationsRoute,
  AuthProfileUserIdOrganizationsRoute: AuthProfileUserIdOrganizationsRoute,
}

const AuthProfileRouteWithChildren = AuthProfileRoute._addFileChildren(
  AuthProfileRouteChildren,
)

interface AuthOrganizationsOrganizationSlugLayoutManageRouteChildren {
  AuthOrganizationsOrganizationSlugLayoutManageInvitationsRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageInvitationsRoute
  AuthOrganizationsOrganizationSlugLayoutManageMembersRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageMembersRoute
  AuthOrganizationsOrganizationSlugLayoutManageSettingsRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageSettingsRoute
}

const AuthOrganizationsOrganizationSlugLayoutManageRouteChildren: AuthOrganizationsOrganizationSlugLayoutManageRouteChildren =
  {
    AuthOrganizationsOrganizationSlugLayoutManageInvitationsRoute:
      AuthOrganizationsOrganizationSlugLayoutManageInvitationsRoute,
    AuthOrganizationsOrganizationSlugLayoutManageMembersRoute:
      AuthOrganizationsOrganizationSlugLayoutManageMembersRoute,
    AuthOrganizationsOrganizationSlugLayoutManageSettingsRoute:
      AuthOrganizationsOrganizationSlugLayoutManageSettingsRoute,
  }

const AuthOrganizationsOrganizationSlugLayoutManageRouteWithChildren =
  AuthOrganizationsOrganizationSlugLayoutManageRoute._addFileChildren(
    AuthOrganizationsOrganizationSlugLayoutManageRouteChildren,
  )

interface AuthOrganizationsOrganizationSlugLayoutRouteChildren {
  AuthOrganizationsOrganizationSlugLayoutManageRoute: typeof AuthOrganizationsOrganizationSlugLayoutManageRouteWithChildren
  AuthOrganizationsOrganizationSlugLayoutIndexRoute: typeof AuthOrganizationsOrganizationSlugLayoutIndexRoute
  AuthOrganizationsOrganizationSlugLayoutProjectsIndexRoute: typeof AuthOrganizationsOrganizationSlugLayoutProjectsIndexRoute
  AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRoute: typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRoute
  AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRoute: typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRoute
  AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRoute: typeof AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRoute
}

const AuthOrganizationsOrganizationSlugLayoutRouteChildren: AuthOrganizationsOrganizationSlugLayoutRouteChildren =
  {
    AuthOrganizationsOrganizationSlugLayoutManageRoute:
      AuthOrganizationsOrganizationSlugLayoutManageRouteWithChildren,
    AuthOrganizationsOrganizationSlugLayoutIndexRoute:
      AuthOrganizationsOrganizationSlugLayoutIndexRoute,
    AuthOrganizationsOrganizationSlugLayoutProjectsIndexRoute:
      AuthOrganizationsOrganizationSlugLayoutProjectsIndexRoute,
    AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRoute:
      AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugFeedbackIdRoute,
    AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRoute:
      AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugSettingsRoute,
    AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRoute:
      AuthOrganizationsOrganizationSlugLayoutProjectsProjectSlugIndexRoute,
  }

const AuthOrganizationsOrganizationSlugLayoutRouteWithChildren =
  AuthOrganizationsOrganizationSlugLayoutRoute._addFileChildren(
    AuthOrganizationsOrganizationSlugLayoutRouteChildren,
  )

interface AuthOrganizationsOrganizationSlugRouteChildren {
  AuthOrganizationsOrganizationSlugLayoutRoute: typeof AuthOrganizationsOrganizationSlugLayoutRouteWithChildren
}

const AuthOrganizationsOrganizationSlugRouteChildren: AuthOrganizationsOrganizationSlugRouteChildren =
  {
    AuthOrganizationsOrganizationSlugLayoutRoute:
      AuthOrganizationsOrganizationSlugLayoutRouteWithChildren,
  }

const AuthOrganizationsOrganizationSlugRouteWithChildren =
  AuthOrganizationsOrganizationSlugRoute._addFileChildren(
    AuthOrganizationsOrganizationSlugRouteChildren,
  )

interface AuthRouteChildren {
  AuthProfileRoute: typeof AuthProfileRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthOrganizationsIndexRoute: typeof AuthOrganizationsIndexRoute
  AuthOrganizationsOrganizationSlugRoute: typeof AuthOrganizationsOrganizationSlugRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRoute: AuthProfileRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthOrganizationsIndexRoute: AuthOrganizationsIndexRoute,
  AuthOrganizationsOrganizationSlugRoute:
    AuthOrganizationsOrganizationSlugRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
