/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInviteRouteImport } from './routes/api/invite'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthWorkspacesIndexRouteImport } from './routes/_auth/workspaces/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthWorkspacesWorkspaceSlugLayoutRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout'
import { Route as AuthProfileUserIdLayoutRouteImport } from './routes/_auth/profile/$userId/_layout'
import { Route as AuthWorkspacesWorkspaceSlugLayoutIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/index'
import { Route as AuthWorkspacesWorkspaceSlugLayoutManageRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/_manage'
import { Route as AuthProfileUserIdLayoutWorkspacesRouteImport } from './routes/_auth/profile/$userId/_layout/workspaces'
import { Route as AuthProfileUserIdLayoutInvitationsRouteImport } from './routes/_auth/profile/$userId/_layout/invitations'
import { Route as AuthProfileUserIdLayoutAccountRouteImport } from './routes/_auth/profile/$userId/_layout/account'
import { Route as AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/projects/index'
import { Route as AuthWorkspacesWorkspaceSlugLayoutManageSettingsRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/_manage/settings'
import { Route as AuthWorkspacesWorkspaceSlugLayoutManageMembersRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/_manage/members'
import { Route as AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/_manage/invitations'
import { Route as AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/index'
import { Route as AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/settings'
import { Route as AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRouteImport } from './routes/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/$feedbackId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInviteRoute = ApiInviteRouteImport.update({
  id: '/api/invite',
  path: '/api/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkspacesIndexRoute = AuthWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspacesWorkspaceSlugLayoutRoute =
  AuthWorkspacesWorkspaceSlugLayoutRouteImport.update({
    id: '/workspaces/$workspaceSlug/_layout',
    path: '/workspaces/$workspaceSlug',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProfileUserIdLayoutRoute = AuthProfileUserIdLayoutRouteImport.update({
  id: '/profile/$userId/_layout',
  path: '/profile/$userId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkspacesWorkspaceSlugLayoutIndexRoute =
  AuthWorkspacesWorkspaceSlugLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugLayoutManageRoute =
  AuthWorkspacesWorkspaceSlugLayoutManageRouteImport.update({
    id: '/_manage',
    getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutRoute,
  } as any)
const AuthProfileUserIdLayoutWorkspacesRoute =
  AuthProfileUserIdLayoutWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthProfileUserIdLayoutRoute,
  } as any)
const AuthProfileUserIdLayoutInvitationsRoute =
  AuthProfileUserIdLayoutInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthProfileUserIdLayoutRoute,
  } as any)
const AuthProfileUserIdLayoutAccountRoute =
  AuthProfileUserIdLayoutAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthProfileUserIdLayoutRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRoute =
  AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugLayoutManageSettingsRoute =
  AuthWorkspacesWorkspaceSlugLayoutManageSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutManageRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugLayoutManageMembersRoute =
  AuthWorkspacesWorkspaceSlugLayoutManageMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutManageRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRoute =
  AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutManageRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRoute =
  AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRouteImport.update({
    id: '/projects/$projectSlug/',
    path: '/projects/$projectSlug/',
    getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRoute =
  AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRouteImport.update(
    {
      id: '/projects/$projectSlug/settings',
      path: '/projects/$projectSlug/settings',
      getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutRoute,
    } as any,
  )
const AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRoute =
  AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRouteImport.update(
    {
      id: '/projects/$projectSlug/$feedbackId',
      path: '/projects/$projectSlug/$feedbackId',
      getParentRoute: () => AuthWorkspacesWorkspaceSlugLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/invite': typeof ApiInviteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces': typeof AuthWorkspacesIndexRoute
  '/profile/$userId': typeof AuthProfileUserIdLayoutRouteWithChildren
  '/workspaces/$workspaceSlug': typeof AuthWorkspacesWorkspaceSlugLayoutManageRouteWithChildren
  '/profile/$userId/account': typeof AuthProfileUserIdLayoutAccountRoute
  '/profile/$userId/invitations': typeof AuthProfileUserIdLayoutInvitationsRoute
  '/profile/$userId/workspaces': typeof AuthProfileUserIdLayoutWorkspacesRoute
  '/workspaces/$workspaceSlug/': typeof AuthWorkspacesWorkspaceSlugLayoutIndexRoute
  '/workspaces/$workspaceSlug/invitations': typeof AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRoute
  '/workspaces/$workspaceSlug/members': typeof AuthWorkspacesWorkspaceSlugLayoutManageMembersRoute
  '/workspaces/$workspaceSlug/settings': typeof AuthWorkspacesWorkspaceSlugLayoutManageSettingsRoute
  '/workspaces/$workspaceSlug/projects': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRoute
  '/workspaces/$workspaceSlug/projects/$projectSlug/$feedbackId': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRoute
  '/workspaces/$workspaceSlug/projects/$projectSlug/settings': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRoute
  '/workspaces/$workspaceSlug/projects/$projectSlug': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/invite': typeof ApiInviteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces': typeof AuthWorkspacesIndexRoute
  '/profile/$userId': typeof AuthProfileUserIdLayoutRouteWithChildren
  '/profile/$userId/account': typeof AuthProfileUserIdLayoutAccountRoute
  '/profile/$userId/invitations': typeof AuthProfileUserIdLayoutInvitationsRoute
  '/profile/$userId/workspaces': typeof AuthProfileUserIdLayoutWorkspacesRoute
  '/workspaces/$workspaceSlug': typeof AuthWorkspacesWorkspaceSlugLayoutIndexRoute
  '/workspaces/$workspaceSlug/invitations': typeof AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRoute
  '/workspaces/$workspaceSlug/members': typeof AuthWorkspacesWorkspaceSlugLayoutManageMembersRoute
  '/workspaces/$workspaceSlug/settings': typeof AuthWorkspacesWorkspaceSlugLayoutManageSettingsRoute
  '/workspaces/$workspaceSlug/projects': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRoute
  '/workspaces/$workspaceSlug/projects/$projectSlug/$feedbackId': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRoute
  '/workspaces/$workspaceSlug/projects/$projectSlug/settings': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRoute
  '/workspaces/$workspaceSlug/projects/$projectSlug': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/api/invite': typeof ApiInviteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/workspaces/': typeof AuthWorkspacesIndexRoute
  '/_auth/profile/$userId/_layout': typeof AuthProfileUserIdLayoutRouteWithChildren
  '/_auth/workspaces/$workspaceSlug/_layout': typeof AuthWorkspacesWorkspaceSlugLayoutRouteWithChildren
  '/_auth/profile/$userId/_layout/account': typeof AuthProfileUserIdLayoutAccountRoute
  '/_auth/profile/$userId/_layout/invitations': typeof AuthProfileUserIdLayoutInvitationsRoute
  '/_auth/profile/$userId/_layout/workspaces': typeof AuthProfileUserIdLayoutWorkspacesRoute
  '/_auth/workspaces/$workspaceSlug/_layout/_manage': typeof AuthWorkspacesWorkspaceSlugLayoutManageRouteWithChildren
  '/_auth/workspaces/$workspaceSlug/_layout/': typeof AuthWorkspacesWorkspaceSlugLayoutIndexRoute
  '/_auth/workspaces/$workspaceSlug/_layout/_manage/invitations': typeof AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRoute
  '/_auth/workspaces/$workspaceSlug/_layout/_manage/members': typeof AuthWorkspacesWorkspaceSlugLayoutManageMembersRoute
  '/_auth/workspaces/$workspaceSlug/_layout/_manage/settings': typeof AuthWorkspacesWorkspaceSlugLayoutManageSettingsRoute
  '/_auth/workspaces/$workspaceSlug/_layout/projects/': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRoute
  '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/$feedbackId': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRoute
  '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/settings': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRoute
  '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/': typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/dashboard'
    | '/api/invite'
    | '/api/auth/$'
    | '/workspaces'
    | '/profile/$userId'
    | '/workspaces/$workspaceSlug'
    | '/profile/$userId/account'
    | '/profile/$userId/invitations'
    | '/profile/$userId/workspaces'
    | '/workspaces/$workspaceSlug/'
    | '/workspaces/$workspaceSlug/invitations'
    | '/workspaces/$workspaceSlug/members'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/projects'
    | '/workspaces/$workspaceSlug/projects/$projectSlug/$feedbackId'
    | '/workspaces/$workspaceSlug/projects/$projectSlug/settings'
    | '/workspaces/$workspaceSlug/projects/$projectSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/dashboard'
    | '/api/invite'
    | '/api/auth/$'
    | '/workspaces'
    | '/profile/$userId'
    | '/profile/$userId/account'
    | '/profile/$userId/invitations'
    | '/profile/$userId/workspaces'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/$workspaceSlug/invitations'
    | '/workspaces/$workspaceSlug/members'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/projects'
    | '/workspaces/$workspaceSlug/projects/$projectSlug/$feedbackId'
    | '/workspaces/$workspaceSlug/projects/$projectSlug/settings'
    | '/workspaces/$workspaceSlug/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/pricing'
    | '/_auth/dashboard'
    | '/api/invite'
    | '/api/auth/$'
    | '/_auth/workspaces/'
    | '/_auth/profile/$userId/_layout'
    | '/_auth/workspaces/$workspaceSlug/_layout'
    | '/_auth/profile/$userId/_layout/account'
    | '/_auth/profile/$userId/_layout/invitations'
    | '/_auth/profile/$userId/_layout/workspaces'
    | '/_auth/workspaces/$workspaceSlug/_layout/_manage'
    | '/_auth/workspaces/$workspaceSlug/_layout/'
    | '/_auth/workspaces/$workspaceSlug/_layout/_manage/invitations'
    | '/_auth/workspaces/$workspaceSlug/_layout/_manage/members'
    | '/_auth/workspaces/$workspaceSlug/_layout/_manage/settings'
    | '/_auth/workspaces/$workspaceSlug/_layout/projects/'
    | '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/$feedbackId'
    | '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/settings'
    | '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiInviteRoute: typeof ApiInviteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invite': {
      id: '/api/invite'
      path: '/api/invite'
      fullPath: '/api/invite'
      preLoaderRoute: typeof ApiInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/': {
      id: '/_auth/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthWorkspacesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/workspaces/$workspaceSlug/_layout': {
      id: '/_auth/workspaces/$workspaceSlug/_layout'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/$userId/_layout': {
      id: '/_auth/profile/$userId/_layout'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthProfileUserIdLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutIndexRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/_manage': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/_manage'
      path: ''
      fullPath: '/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutRoute
    }
    '/_auth/profile/$userId/_layout/workspaces': {
      id: '/_auth/profile/$userId/_layout/workspaces'
      path: '/workspaces'
      fullPath: '/profile/$userId/workspaces'
      preLoaderRoute: typeof AuthProfileUserIdLayoutWorkspacesRouteImport
      parentRoute: typeof AuthProfileUserIdLayoutRoute
    }
    '/_auth/profile/$userId/_layout/invitations': {
      id: '/_auth/profile/$userId/_layout/invitations'
      path: '/invitations'
      fullPath: '/profile/$userId/invitations'
      preLoaderRoute: typeof AuthProfileUserIdLayoutInvitationsRouteImport
      parentRoute: typeof AuthProfileUserIdLayoutRoute
    }
    '/_auth/profile/$userId/_layout/account': {
      id: '/_auth/profile/$userId/_layout/account'
      path: '/account'
      fullPath: '/profile/$userId/account'
      preLoaderRoute: typeof AuthProfileUserIdLayoutAccountRouteImport
      parentRoute: typeof AuthProfileUserIdLayoutRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/projects/': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/projects/'
      path: '/projects'
      fullPath: '/workspaces/$workspaceSlug/projects'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/_manage/settings': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/_manage/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageSettingsRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/_manage/members': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/_manage/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceSlug/members'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageMembersRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/_manage/invitations': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/_manage/invitations'
      path: '/invitations'
      fullPath: '/workspaces/$workspaceSlug/invitations'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/'
      path: '/projects/$projectSlug'
      fullPath: '/workspaces/$workspaceSlug/projects/$projectSlug'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/settings': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/settings'
      path: '/projects/$projectSlug/settings'
      fullPath: '/workspaces/$workspaceSlug/projects/$projectSlug/settings'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutRoute
    }
    '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/$feedbackId': {
      id: '/_auth/workspaces/$workspaceSlug/_layout/projects/$projectSlug/$feedbackId'
      path: '/projects/$projectSlug/$feedbackId'
      fullPath: '/workspaces/$workspaceSlug/projects/$projectSlug/$feedbackId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRouteImport
      parentRoute: typeof AuthWorkspacesWorkspaceSlugLayoutRoute
    }
  }
}

interface AuthProfileUserIdLayoutRouteChildren {
  AuthProfileUserIdLayoutAccountRoute: typeof AuthProfileUserIdLayoutAccountRoute
  AuthProfileUserIdLayoutInvitationsRoute: typeof AuthProfileUserIdLayoutInvitationsRoute
  AuthProfileUserIdLayoutWorkspacesRoute: typeof AuthProfileUserIdLayoutWorkspacesRoute
}

const AuthProfileUserIdLayoutRouteChildren: AuthProfileUserIdLayoutRouteChildren =
  {
    AuthProfileUserIdLayoutAccountRoute: AuthProfileUserIdLayoutAccountRoute,
    AuthProfileUserIdLayoutInvitationsRoute:
      AuthProfileUserIdLayoutInvitationsRoute,
    AuthProfileUserIdLayoutWorkspacesRoute:
      AuthProfileUserIdLayoutWorkspacesRoute,
  }

const AuthProfileUserIdLayoutRouteWithChildren =
  AuthProfileUserIdLayoutRoute._addFileChildren(
    AuthProfileUserIdLayoutRouteChildren,
  )

interface AuthWorkspacesWorkspaceSlugLayoutManageRouteChildren {
  AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRoute
  AuthWorkspacesWorkspaceSlugLayoutManageMembersRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageMembersRoute
  AuthWorkspacesWorkspaceSlugLayoutManageSettingsRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageSettingsRoute
}

const AuthWorkspacesWorkspaceSlugLayoutManageRouteChildren: AuthWorkspacesWorkspaceSlugLayoutManageRouteChildren =
  {
    AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRoute:
      AuthWorkspacesWorkspaceSlugLayoutManageInvitationsRoute,
    AuthWorkspacesWorkspaceSlugLayoutManageMembersRoute:
      AuthWorkspacesWorkspaceSlugLayoutManageMembersRoute,
    AuthWorkspacesWorkspaceSlugLayoutManageSettingsRoute:
      AuthWorkspacesWorkspaceSlugLayoutManageSettingsRoute,
  }

const AuthWorkspacesWorkspaceSlugLayoutManageRouteWithChildren =
  AuthWorkspacesWorkspaceSlugLayoutManageRoute._addFileChildren(
    AuthWorkspacesWorkspaceSlugLayoutManageRouteChildren,
  )

interface AuthWorkspacesWorkspaceSlugLayoutRouteChildren {
  AuthWorkspacesWorkspaceSlugLayoutManageRoute: typeof AuthWorkspacesWorkspaceSlugLayoutManageRouteWithChildren
  AuthWorkspacesWorkspaceSlugLayoutIndexRoute: typeof AuthWorkspacesWorkspaceSlugLayoutIndexRoute
  AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRoute: typeof AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRoute
  AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRoute: typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRoute
  AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRoute: typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRoute
  AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRoute: typeof AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRoute
}

const AuthWorkspacesWorkspaceSlugLayoutRouteChildren: AuthWorkspacesWorkspaceSlugLayoutRouteChildren =
  {
    AuthWorkspacesWorkspaceSlugLayoutManageRoute:
      AuthWorkspacesWorkspaceSlugLayoutManageRouteWithChildren,
    AuthWorkspacesWorkspaceSlugLayoutIndexRoute:
      AuthWorkspacesWorkspaceSlugLayoutIndexRoute,
    AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRoute:
      AuthWorkspacesWorkspaceSlugLayoutProjectsIndexRoute,
    AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRoute:
      AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugFeedbackIdRoute,
    AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRoute:
      AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugSettingsRoute,
    AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRoute:
      AuthWorkspacesWorkspaceSlugLayoutProjectsProjectSlugIndexRoute,
  }

const AuthWorkspacesWorkspaceSlugLayoutRouteWithChildren =
  AuthWorkspacesWorkspaceSlugLayoutRoute._addFileChildren(
    AuthWorkspacesWorkspaceSlugLayoutRouteChildren,
  )

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthWorkspacesIndexRoute: typeof AuthWorkspacesIndexRoute
  AuthProfileUserIdLayoutRoute: typeof AuthProfileUserIdLayoutRouteWithChildren
  AuthWorkspacesWorkspaceSlugLayoutRoute: typeof AuthWorkspacesWorkspaceSlugLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthWorkspacesIndexRoute: AuthWorkspacesIndexRoute,
  AuthProfileUserIdLayoutRoute: AuthProfileUserIdLayoutRouteWithChildren,
  AuthWorkspacesWorkspaceSlugLayoutRoute:
    AuthWorkspacesWorkspaceSlugLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiInviteRoute: ApiInviteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
