name: Test 🧪

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_unit:
    name: Run unit tests 🃏
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # - uses: ArtiomTr/jest-coverage-report-action@v2
      #   with:
      #     package-manager: bun
      #     test-script: bun test:coverage
      #     annotations: failed-tests
      # TODO replace below with commented job above, blocked by Bun not yet supporting a JSON coverage reporter for the action to consume nor generate (similar: https://github.com/oven-sh/bun/issues/4099)
      - name: Install dependencies
        run: bun install
      - name: Run unit tests
        run: bun run test

  test_e2e:
    name: Run E2E tests 🗺️
    timeout-minutes: 3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # shard tests across 4 nodes (https://playwright.dev/docs/test-sharding)
      matrix:
        # NB: simple numeric shard names are used here instead of the more common practice of e.g. 1/N, 2/N, ... to resolve a GitHub Actions error if unsupported characters across filesystems are found and used in artifact file paths (e.g. NTFS doesn't support `/`). GitHub implemented this validation check to enable better cross-platform support. Since the matrix shard ID is used in artifact uploads below, using `/` would throw an error.
        shard: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install Playwright
        run: bunx playwright install --with-deps
      - name: Run E2E tests
        run: bun test:e2e --shard ${{ matrix.shard }}
      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-shard-${{ matrix.shard }}
          path: blob-report
          retention-days: 1

  merge_e2e_reports:
    # merge reports after E2E test execution, even if some shards have failed
    if: always()
    needs: [test_e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-blob-reports
          path: all-blob-reports
      - name: Merge into HTML report
        run: bunx playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report-attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14
